// GENERATED by scripts/build-portrait-manifest.mjs — do not edit by hand.

export type PortraitOption = {
  /** The cell's position in the original 6-wide sheet grid. */
  id: string;
  /** Every sheet that has a piece of this option, in no particular order. */
  sheets: string[];
};

export const OPTIONS: Record<string, PortraitOption[]> = {
  "jaw": [
    {
      "id": "00",
      "sheets": [
        "Jaws"
      ]
    },
    {
      "id": "01",
      "sheets": [
        "Jaws"
      ]
    },
    {
      "id": "02",
      "sheets": [
        "Jaws"
      ]
    },
    {
      "id": "03",
      "sheets": [
        "Jaws"
      ]
    },
    {
      "id": "04",
      "sheets": [
        "Jaws"
      ]
    },
    {
      "id": "05",
      "sheets": [
        "Jaws"
      ]
    },
    {
      "id": "06",
      "sheets": [
        "Jaws"
      ]
    },
    {
      "id": "07",
      "sheets": [
        "Jaws"
      ]
    },
    {
      "id": "08",
      "sheets": [
        "Jaws"
      ]
    },
    {
      "id": "09",
      "sheets": [
        "Jaws"
      ]
    },
    {
      "id": "10",
      "sheets": [
        "Jaws"
      ]
    },
    {
      "id": "11",
      "sheets": [
        "Jaws"
      ]
    },
    {
      "id": "12",
      "sheets": [
        "Jaws"
      ]
    },
    {
      "id": "13",
      "sheets": [
        "Jaws"
      ]
    },
    {
      "id": "14",
      "sheets": [
        "Jaws"
      ]
    },
    {
      "id": "15",
      "sheets": [
        "Jaws"
      ]
    },
    {
      "id": "16",
      "sheets": [
        "Jaws"
      ]
    },
    {
      "id": "17",
      "sheets": [
        "Jaws"
      ]
    },
    {
      "id": "18",
      "sheets": [
        "Jaws"
      ]
    },
    {
      "id": "19",
      "sheets": [
        "Jaws"
      ]
    },
    {
      "id": "20",
      "sheets": [
        "Jaws"
      ]
    },
    {
      "id": "21",
      "sheets": [
        "Jaws"
      ]
    },
    {
      "id": "22",
      "sheets": [
        "Jaws"
      ]
    },
    {
      "id": "23",
      "sheets": [
        "Jaws"
      ]
    },
    {
      "id": "24",
      "sheets": [
        "Jaws"
      ]
    },
    {
      "id": "25",
      "sheets": [
        "Jaws"
      ]
    }
  ],
  "ears": [
    {
      "id": "00",
      "sheets": [
        "EarsFront"
      ]
    },
    {
      "id": "01",
      "sheets": [
        "EarsFront"
      ]
    },
    {
      "id": "02",
      "sheets": [
        "EarsFront",
        "EarsBack"
      ]
    },
    {
      "id": "03",
      "sheets": [
        "EarsFront"
      ]
    },
    {
      "id": "04",
      "sheets": [
        "EarsFront"
      ]
    },
    {
      "id": "05",
      "sheets": [
        "EarsFront",
        "EarsBack"
      ]
    },
    {
      "id": "06",
      "sheets": [
        "EarsFront",
        "EarsBack"
      ]
    },
    {
      "id": "07",
      "sheets": [
        "EarsFront"
      ]
    },
    {
      "id": "08",
      "sheets": [
        "EarsFront"
      ]
    },
    {
      "id": "09",
      "sheets": [
        "EarsFront",
        "EarsBack"
      ]
    },
    {
      "id": "10",
      "sheets": [
        "EarsFront",
        "EarsBack"
      ]
    },
    {
      "id": "11",
      "sheets": [
        "EarsFront",
        "EarsBack"
      ]
    },
    {
      "id": "12",
      "sheets": [
        "EarsFront",
        "EarsBack"
      ]
    },
    {
      "id": "13",
      "sheets": [
        "EarsFront",
        "EarsBack"
      ]
    }
  ],
  "eyes": [
    {
      "id": "00",
      "sheets": [
        "Eyes",
        "pupils"
      ]
    },
    {
      "id": "01",
      "sheets": [
        "Eyes",
        "pupils"
      ]
    },
    {
      "id": "02",
      "sheets": [
        "Eyes",
        "pupils"
      ]
    },
    {
      "id": "03",
      "sheets": [
        "Eyes",
        "pupils"
      ]
    },
    {
      "id": "04",
      "sheets": [
        "Eyes",
        "pupils"
      ]
    },
    {
      "id": "05",
      "sheets": [
        "Eyes",
        "pupils"
      ]
    },
    {
      "id": "06",
      "sheets": [
        "Eyes",
        "pupils"
      ]
    },
    {
      "id": "07",
      "sheets": [
        "Eyes",
        "pupils"
      ]
    },
    {
      "id": "08",
      "sheets": [
        "Eyes",
        "pupils"
      ]
    },
    {
      "id": "09",
      "sheets": [
        "Eyes",
        "pupils"
      ]
    },
    {
      "id": "10",
      "sheets": [
        "Eyes",
        "pupils"
      ]
    },
    {
      "id": "11",
      "sheets": [
        "Eyes",
        "pupils"
      ]
    },
    {
      "id": "12",
      "sheets": [
        "Eyes",
        "pupils"
      ]
    },
    {
      "id": "13",
      "sheets": [
        "Eyes",
        "pupils"
      ]
    },
    {
      "id": "14",
      "sheets": [
        "Eyes",
        "pupils"
      ]
    },
    {
      "id": "15",
      "sheets": [
        "Eyes",
        "pupils"
      ]
    },
    {
      "id": "16",
      "sheets": [
        "Eyes"
      ]
    },
    {
      "id": "17",
      "sheets": [
        "Eyes",
        "pupils"
      ]
    },
    {
      "id": "18",
      "sheets": [
        "Eyes",
        "pupils"
      ]
    },
    {
      "id": "19",
      "sheets": [
        "Eyes",
        "pupils"
      ]
    },
    {
      "id": "20",
      "sheets": [
        "Eyes"
      ]
    },
    {
      "id": "21",
      "sheets": [
        "Eyes"
      ]
    },
    {
      "id": "22",
      "sheets": [
        "Eyes"
      ]
    },
    {
      "id": "23",
      "sheets": [
        "Eyes"
      ]
    },
    {
      "id": "24",
      "sheets": [
        "Eyes"
      ]
    },
    {
      "id": "25",
      "sheets": [
        "Eyes"
      ]
    }
  ],
  "eyebrows": [
    {
      "id": "00",
      "sheets": [
        "Eyebrows"
      ]
    },
    {
      "id": "01",
      "sheets": [
        "Eyebrows"
      ]
    },
    {
      "id": "02",
      "sheets": [
        "Eyebrows"
      ]
    },
    {
      "id": "03",
      "sheets": [
        "Eyebrows"
      ]
    },
    {
      "id": "04",
      "sheets": [
        "Eyebrows"
      ]
    },
    {
      "id": "05",
      "sheets": [
        "Eyebrows"
      ]
    },
    {
      "id": "06",
      "sheets": [
        "Eyebrows"
      ]
    },
    {
      "id": "07",
      "sheets": [
        "Eyebrows"
      ]
    },
    {
      "id": "08",
      "sheets": [
        "Eyebrows"
      ]
    },
    {
      "id": "09",
      "sheets": [
        "Eyebrows"
      ]
    },
    {
      "id": "10",
      "sheets": [
        "Eyebrows"
      ]
    },
    {
      "id": "11",
      "sheets": [
        "Eyebrows"
      ]
    },
    {
      "id": "12",
      "sheets": [
        "Eyebrows"
      ]
    },
    {
      "id": "13",
      "sheets": [
        "Eyebrows"
      ]
    },
    {
      "id": "14",
      "sheets": [
        "Eyebrows"
      ]
    }
  ],
  "nose": [
    {
      "id": "00",
      "sheets": [
        "Noses"
      ]
    },
    {
      "id": "01",
      "sheets": [
        "Noses"
      ]
    },
    {
      "id": "02",
      "sheets": [
        "Noses"
      ]
    },
    {
      "id": "03",
      "sheets": [
        "Noses"
      ]
    },
    {
      "id": "04",
      "sheets": [
        "Noses"
      ]
    },
    {
      "id": "05",
      "sheets": [
        "Noses"
      ]
    },
    {
      "id": "06",
      "sheets": [
        "Noses"
      ]
    },
    {
      "id": "07",
      "sheets": [
        "Noses"
      ]
    },
    {
      "id": "08",
      "sheets": [
        "Noses"
      ]
    },
    {
      "id": "09",
      "sheets": [
        "Noses"
      ]
    },
    {
      "id": "10",
      "sheets": [
        "Noses"
      ]
    },
    {
      "id": "11",
      "sheets": [
        "Noses"
      ]
    },
    {
      "id": "12",
      "sheets": [
        "Noses"
      ]
    },
    {
      "id": "13",
      "sheets": [
        "Noses"
      ]
    },
    {
      "id": "14",
      "sheets": [
        "Noses"
      ]
    },
    {
      "id": "15",
      "sheets": [
        "Noses"
      ]
    }
  ],
  "mouth": [
    {
      "id": "00",
      "sheets": [
        "Mouths"
      ]
    },
    {
      "id": "01",
      "sheets": [
        "Mouths"
      ]
    },
    {
      "id": "02",
      "sheets": [
        "Mouths"
      ]
    },
    {
      "id": "03",
      "sheets": [
        "Mouths"
      ]
    },
    {
      "id": "04",
      "sheets": [
        "Mouths"
      ]
    },
    {
      "id": "05",
      "sheets": [
        "Mouths"
      ]
    },
    {
      "id": "06",
      "sheets": [
        "Mouths"
      ]
    },
    {
      "id": "07",
      "sheets": [
        "Mouths"
      ]
    },
    {
      "id": "08",
      "sheets": [
        "Mouths"
      ]
    },
    {
      "id": "09",
      "sheets": [
        "Mouths"
      ]
    },
    {
      "id": "10",
      "sheets": [
        "Mouths"
      ]
    },
    {
      "id": "11",
      "sheets": [
        "Mouths"
      ]
    },
    {
      "id": "12",
      "sheets": [
        "Mouths"
      ]
    },
    {
      "id": "13",
      "sheets": [
        "Mouths"
      ]
    },
    {
      "id": "14",
      "sheets": [
        "Mouths"
      ]
    },
    {
      "id": "15",
      "sheets": [
        "Mouths"
      ]
    },
    {
      "id": "16",
      "sheets": [
        "Mouths"
      ]
    },
    {
      "id": "17",
      "sheets": [
        "Mouths"
      ]
    },
    {
      "id": "18",
      "sheets": [
        "Mouths"
      ]
    },
    {
      "id": "19",
      "sheets": [
        "Mouths"
      ]
    },
    {
      "id": "20",
      "sheets": [
        "Mouths"
      ]
    },
    {
      "id": "21",
      "sheets": [
        "Mouths"
      ]
    },
    {
      "id": "22",
      "sheets": [
        "Mouths"
      ]
    },
    {
      "id": "23",
      "sheets": [
        "Mouths"
      ]
    },
    {
      "id": "24",
      "sheets": [
        "Mouths"
      ]
    },
    {
      "id": "25",
      "sheets": [
        "Mouths"
      ]
    },
    {
      "id": "26",
      "sheets": [
        "Mouths"
      ]
    },
    {
      "id": "27",
      "sheets": [
        "Mouths"
      ]
    }
  ],
  "beard": [
    {
      "id": "01",
      "sheets": [
        "Beards"
      ]
    },
    {
      "id": "02",
      "sheets": [
        "Beards"
      ]
    },
    {
      "id": "03",
      "sheets": [
        "Beards"
      ]
    },
    {
      "id": "04",
      "sheets": [
        "Beards"
      ]
    },
    {
      "id": "05",
      "sheets": [
        "Beards"
      ]
    },
    {
      "id": "06",
      "sheets": [
        "Beards"
      ]
    },
    {
      "id": "07",
      "sheets": [
        "Beards"
      ]
    },
    {
      "id": "08",
      "sheets": [
        "Beards"
      ]
    },
    {
      "id": "09",
      "sheets": [
        "Beards"
      ]
    },
    {
      "id": "10",
      "sheets": [
        "Beards"
      ]
    },
    {
      "id": "11",
      "sheets": [
        "Beards"
      ]
    },
    {
      "id": "12",
      "sheets": [
        "Beards"
      ]
    },
    {
      "id": "13",
      "sheets": [
        "Beards"
      ]
    }
  ],
  "hair": [
    {
      "id": "01",
      "sheets": [
        "HairBack",
        "HairFront"
      ]
    },
    {
      "id": "02",
      "sheets": [
        "HairBack",
        "HairFront"
      ]
    },
    {
      "id": "03",
      "sheets": [
        "HairBack",
        "HairFront"
      ]
    },
    {
      "id": "04",
      "sheets": [
        "HairBack",
        "HairFront"
      ]
    },
    {
      "id": "05",
      "sheets": [
        "HairBack",
        "HairFront"
      ]
    },
    {
      "id": "06",
      "sheets": [
        "HairBack",
        "HairFront"
      ]
    },
    {
      "id": "07",
      "sheets": [
        "HairBack",
        "HairFront"
      ]
    },
    {
      "id": "08",
      "sheets": [
        "HairBack",
        "HairFront"
      ]
    },
    {
      "id": "09",
      "sheets": [
        "HairBack",
        "HairFront"
      ]
    },
    {
      "id": "10",
      "sheets": [
        "HairBack",
        "HairFront"
      ]
    },
    {
      "id": "11",
      "sheets": [
        "HairBack",
        "HairFront"
      ]
    },
    {
      "id": "12",
      "sheets": [
        "HairBack",
        "HairFront"
      ]
    },
    {
      "id": "13",
      "sheets": [
        "HairBack",
        "HairFront"
      ]
    },
    {
      "id": "14",
      "sheets": [
        "HairBack",
        "HairFront"
      ]
    },
    {
      "id": "15",
      "sheets": [
        "HairBack",
        "HairFront"
      ]
    },
    {
      "id": "16",
      "sheets": [
        "HairBack",
        "HairFront"
      ]
    },
    {
      "id": "17",
      "sheets": [
        "HairBack",
        "HairFront"
      ]
    },
    {
      "id": "18",
      "sheets": [
        "HairBack",
        "HairFront"
      ]
    },
    {
      "id": "19",
      "sheets": [
        "HairBack",
        "HairFront"
      ]
    },
    {
      "id": "20",
      "sheets": [
        "HairBack",
        "HairFront"
      ]
    },
    {
      "id": "21",
      "sheets": [
        "HairBack",
        "HairFront"
      ]
    },
    {
      "id": "22",
      "sheets": [
        "HairBack",
        "HairFront"
      ]
    },
    {
      "id": "23",
      "sheets": [
        "HairBack",
        "HairFront"
      ]
    },
    {
      "id": "24",
      "sheets": [
        "HairBack",
        "HairFront"
      ]
    },
    {
      "id": "25",
      "sheets": [
        "HairBack",
        "HairFront"
      ]
    },
    {
      "id": "26",
      "sheets": [
        "HairBack",
        "HairFront"
      ]
    },
    {
      "id": "27",
      "sheets": [
        "HairBack",
        "HairFront"
      ]
    }
  ],
  "misc": [
    {
      "id": "01",
      "sheets": [
        "AccessoriesBelowBeard",
        "LayeredAccessories"
      ]
    },
    {
      "id": "02",
      "sheets": [
        "AccessoriesBelowBeard",
        "LayeredAccessories"
      ]
    },
    {
      "id": "03",
      "sheets": [
        "AccessoriesBelowBeard",
        "LayeredAccessories"
      ]
    },
    {
      "id": "04",
      "sheets": [
        "AccessoriesBelowBeard",
        "LayeredAccessories",
        "LayeredAccessoryBack"
      ]
    },
    {
      "id": "05",
      "sheets": [
        "AccessoriesBelowBeard",
        "LayeredAccessories",
        "LayeredAccessoryBack"
      ]
    },
    {
      "id": "06",
      "sheets": [
        "AccessoriesBelowBeard",
        "LayeredAccessories"
      ]
    },
    {
      "id": "07",
      "sheets": [
        "AccessoriesBelowBeard",
        "LayeredAccessories"
      ]
    },
    {
      "id": "08",
      "sheets": [
        "AccessoriesBelowBeard",
        "LayeredAccessories"
      ]
    },
    {
      "id": "09",
      "sheets": [
        "AccessoriesBelowBeard",
        "LayeredAccessories"
      ]
    },
    {
      "id": "10",
      "sheets": [
        "AccessoriesBelowBeard",
        "LayeredAccessories"
      ]
    },
    {
      "id": "11",
      "sheets": [
        "AccessoriesBelowBeard",
        "LayeredAccessories"
      ]
    },
    {
      "id": "12",
      "sheets": [
        "AccessoriesBelowBeard"
      ]
    },
    {
      "id": "13",
      "sheets": [
        "AccessoriesBelowBeard"
      ]
    },
    {
      "id": "14",
      "sheets": [
        "AccessoriesBelowBeard"
      ]
    }
  ]
};
