// GENERATED by scripts/build-portrait-manifest.mjs — do not edit by hand.

export type PortraitOption = {
  /** The cell's grid index on the sheet it came from. */
  id: string;
  /** Every cell this option draws, as sheet/index. Order is decided by the
   *  compositor's sheet order, not by this list. A cell may carry a {key}
   *  token, filled from the face's own choice for that control. */
  cells: string[];
};

export const OPTIONS: Record<string, PortraitOption[]> = {
  "jaw": [
    {
      "id": "00",
      "cells": [
        "Jaws/00"
      ]
    },
    {
      "id": "01",
      "cells": [
        "Jaws/01"
      ]
    },
    {
      "id": "02",
      "cells": [
        "Jaws/02"
      ]
    },
    {
      "id": "03",
      "cells": [
        "Jaws/03"
      ]
    },
    {
      "id": "04",
      "cells": [
        "Jaws/04"
      ]
    },
    {
      "id": "05",
      "cells": [
        "Jaws/05"
      ]
    },
    {
      "id": "06",
      "cells": [
        "Jaws/06"
      ]
    },
    {
      "id": "07",
      "cells": [
        "Jaws/07"
      ]
    },
    {
      "id": "08",
      "cells": [
        "Jaws/08"
      ]
    },
    {
      "id": "09",
      "cells": [
        "Jaws/09"
      ]
    },
    {
      "id": "10",
      "cells": [
        "Jaws/10"
      ]
    },
    {
      "id": "11",
      "cells": [
        "Jaws/11"
      ]
    },
    {
      "id": "12",
      "cells": [
        "Jaws/12"
      ]
    },
    {
      "id": "13",
      "cells": [
        "Jaws/13"
      ]
    },
    {
      "id": "14",
      "cells": [
        "Jaws/14"
      ]
    },
    {
      "id": "15",
      "cells": [
        "Jaws/15"
      ]
    },
    {
      "id": "16",
      "cells": [
        "Jaws/16"
      ]
    },
    {
      "id": "17",
      "cells": [
        "Jaws/17"
      ]
    },
    {
      "id": "18",
      "cells": [
        "Jaws/18"
      ]
    },
    {
      "id": "19",
      "cells": [
        "Jaws/19"
      ]
    },
    {
      "id": "20",
      "cells": [
        "Jaws/20"
      ]
    },
    {
      "id": "21",
      "cells": [
        "Jaws/21"
      ]
    },
    {
      "id": "22",
      "cells": [
        "Jaws/22"
      ]
    },
    {
      "id": "23",
      "cells": [
        "Jaws/23"
      ]
    },
    {
      "id": "24",
      "cells": [
        "Jaws/24"
      ]
    },
    {
      "id": "25",
      "cells": [
        "Jaws/25"
      ]
    }
  ],
  "ears": [
    {
      "id": "00",
      "cells": [
        "EarsFront/00"
      ]
    },
    {
      "id": "01",
      "cells": [
        "EarsFront/01"
      ]
    },
    {
      "id": "02",
      "cells": [
        "EarsFront/02",
        "EarsBack/02"
      ]
    },
    {
      "id": "03",
      "cells": [
        "EarsFront/03"
      ]
    },
    {
      "id": "04",
      "cells": [
        "EarsFront/04"
      ]
    },
    {
      "id": "05",
      "cells": [
        "EarsFront/05",
        "EarsBack/05"
      ]
    },
    {
      "id": "06",
      "cells": [
        "EarsFront/06",
        "EarsBack/06"
      ]
    },
    {
      "id": "07",
      "cells": [
        "EarsFront/07"
      ]
    },
    {
      "id": "08",
      "cells": [
        "EarsFront/08"
      ]
    },
    {
      "id": "09",
      "cells": [
        "EarsFront/09",
        "EarsBack/09"
      ]
    },
    {
      "id": "10",
      "cells": [
        "EarsFront/10",
        "EarsBack/10"
      ]
    },
    {
      "id": "11",
      "cells": [
        "EarsFront/11",
        "EarsBack/11"
      ]
    },
    {
      "id": "12",
      "cells": [
        "EarsFront/12",
        "EarsBack/12"
      ]
    },
    {
      "id": "13",
      "cells": [
        "EarsFront/13",
        "EarsBack/13"
      ]
    }
  ],
  "eyes": [
    {
      "id": "00",
      "cells": [
        "Eyes/00",
        "pupils/00"
      ]
    },
    {
      "id": "01",
      "cells": [
        "Eyes/01",
        "pupils/01"
      ]
    },
    {
      "id": "02",
      "cells": [
        "Eyes/02",
        "pupils/02"
      ]
    },
    {
      "id": "03",
      "cells": [
        "Eyes/03",
        "pupils/03"
      ]
    },
    {
      "id": "04",
      "cells": [
        "Eyes/04",
        "pupils/04"
      ]
    },
    {
      "id": "05",
      "cells": [
        "Eyes/05",
        "pupils/05"
      ]
    },
    {
      "id": "06",
      "cells": [
        "Eyes/06",
        "pupils/06"
      ]
    },
    {
      "id": "07",
      "cells": [
        "Eyes/07",
        "pupils/07"
      ]
    },
    {
      "id": "08",
      "cells": [
        "Eyes/08",
        "pupils/08"
      ]
    },
    {
      "id": "09",
      "cells": [
        "Eyes/09",
        "pupils/09"
      ]
    },
    {
      "id": "10",
      "cells": [
        "Eyes/10",
        "pupils/10"
      ]
    },
    {
      "id": "11",
      "cells": [
        "Eyes/11",
        "pupils/11"
      ]
    },
    {
      "id": "12",
      "cells": [
        "Eyes/12",
        "pupils/12"
      ]
    },
    {
      "id": "13",
      "cells": [
        "Eyes/13",
        "pupils/13"
      ]
    },
    {
      "id": "14",
      "cells": [
        "Eyes/14",
        "pupils/14"
      ]
    },
    {
      "id": "15",
      "cells": [
        "Eyes/15",
        "pupils/15"
      ]
    },
    {
      "id": "16",
      "cells": [
        "Eyes/16"
      ]
    },
    {
      "id": "17",
      "cells": [
        "Eyes/17",
        "pupils/17"
      ]
    },
    {
      "id": "18",
      "cells": [
        "Eyes/18",
        "pupils/18"
      ]
    },
    {
      "id": "19",
      "cells": [
        "Eyes/19",
        "pupils/19"
      ]
    },
    {
      "id": "20",
      "cells": [
        "Eyes/20"
      ]
    },
    {
      "id": "21",
      "cells": [
        "Eyes/21"
      ]
    },
    {
      "id": "22",
      "cells": [
        "Eyes/22"
      ]
    },
    {
      "id": "23",
      "cells": [
        "Eyes/23"
      ]
    },
    {
      "id": "24",
      "cells": [
        "Eyes/24"
      ]
    },
    {
      "id": "25",
      "cells": [
        "Eyes/25"
      ]
    }
  ],
  "eyebrows": [
    {
      "id": "00",
      "cells": [
        "Eyebrows/00"
      ]
    },
    {
      "id": "01",
      "cells": [
        "Eyebrows/01"
      ]
    },
    {
      "id": "02",
      "cells": [
        "Eyebrows/02"
      ]
    },
    {
      "id": "03",
      "cells": [
        "Eyebrows/03"
      ]
    },
    {
      "id": "04",
      "cells": [
        "Eyebrows/04"
      ]
    },
    {
      "id": "05",
      "cells": [
        "Eyebrows/05"
      ]
    },
    {
      "id": "06",
      "cells": [
        "Eyebrows/06"
      ]
    },
    {
      "id": "07",
      "cells": [
        "Eyebrows/07"
      ]
    },
    {
      "id": "08",
      "cells": [
        "Eyebrows/08"
      ]
    },
    {
      "id": "09",
      "cells": [
        "Eyebrows/09"
      ]
    },
    {
      "id": "10",
      "cells": [
        "Eyebrows/10"
      ]
    },
    {
      "id": "11",
      "cells": [
        "Eyebrows/11"
      ]
    },
    {
      "id": "12",
      "cells": [
        "Eyebrows/12"
      ]
    },
    {
      "id": "13",
      "cells": [
        "Eyebrows/13"
      ]
    },
    {
      "id": "14",
      "cells": [
        "Eyebrows/14"
      ]
    }
  ],
  "nose": [
    {
      "id": "00",
      "cells": [
        "Noses/00"
      ]
    },
    {
      "id": "01",
      "cells": [
        "Noses/01"
      ]
    },
    {
      "id": "02",
      "cells": [
        "Noses/02"
      ]
    },
    {
      "id": "03",
      "cells": [
        "Noses/03"
      ]
    },
    {
      "id": "04",
      "cells": [
        "Noses/04"
      ]
    },
    {
      "id": "05",
      "cells": [
        "Noses/05"
      ]
    },
    {
      "id": "06",
      "cells": [
        "Noses/06"
      ]
    },
    {
      "id": "07",
      "cells": [
        "Noses/07"
      ]
    },
    {
      "id": "08",
      "cells": [
        "Noses/08"
      ]
    },
    {
      "id": "09",
      "cells": [
        "Noses/09"
      ]
    },
    {
      "id": "10",
      "cells": [
        "Noses/10"
      ]
    },
    {
      "id": "11",
      "cells": [
        "Noses/11"
      ]
    },
    {
      "id": "12",
      "cells": [
        "Noses/12"
      ]
    },
    {
      "id": "13",
      "cells": [
        "Noses/13"
      ]
    },
    {
      "id": "14",
      "cells": [
        "Noses/14"
      ]
    },
    {
      "id": "15",
      "cells": [
        "Noses/15"
      ]
    }
  ],
  "mouth": [
    {
      "id": "00",
      "cells": [
        "Mouths/00"
      ]
    },
    {
      "id": "01",
      "cells": [
        "Mouths/01"
      ]
    },
    {
      "id": "02",
      "cells": [
        "Mouths/02"
      ]
    },
    {
      "id": "03",
      "cells": [
        "Mouths/03"
      ]
    },
    {
      "id": "04",
      "cells": [
        "Mouths/04"
      ]
    },
    {
      "id": "05",
      "cells": [
        "Mouths/05"
      ]
    },
    {
      "id": "06",
      "cells": [
        "Mouths/06"
      ]
    },
    {
      "id": "07",
      "cells": [
        "Mouths/07"
      ]
    },
    {
      "id": "08",
      "cells": [
        "Mouths/08"
      ]
    },
    {
      "id": "09",
      "cells": [
        "Mouths/09"
      ]
    },
    {
      "id": "10",
      "cells": [
        "Mouths/10"
      ]
    },
    {
      "id": "11",
      "cells": [
        "Mouths/11"
      ]
    },
    {
      "id": "12",
      "cells": [
        "Mouths/12"
      ]
    },
    {
      "id": "13",
      "cells": [
        "Mouths/13"
      ]
    },
    {
      "id": "14",
      "cells": [
        "Mouths/14"
      ]
    },
    {
      "id": "15",
      "cells": [
        "Mouths/15"
      ]
    },
    {
      "id": "16",
      "cells": [
        "Mouths/16"
      ]
    },
    {
      "id": "17",
      "cells": [
        "Mouths/17"
      ]
    },
    {
      "id": "18",
      "cells": [
        "Mouths/18"
      ]
    },
    {
      "id": "19",
      "cells": [
        "Mouths/19"
      ]
    },
    {
      "id": "20",
      "cells": [
        "Mouths/20"
      ]
    },
    {
      "id": "21",
      "cells": [
        "Mouths/21"
      ]
    },
    {
      "id": "22",
      "cells": [
        "Mouths/22"
      ]
    },
    {
      "id": "23",
      "cells": [
        "Mouths/23"
      ]
    },
    {
      "id": "24",
      "cells": [
        "Mouths/24"
      ]
    },
    {
      "id": "25",
      "cells": [
        "Mouths/25"
      ]
    },
    {
      "id": "26",
      "cells": [
        "Mouths/26"
      ]
    },
    {
      "id": "27",
      "cells": [
        "Mouths/27"
      ]
    }
  ],
  "beard": [
    {
      "id": "01",
      "cells": [
        "Beards/01"
      ]
    },
    {
      "id": "02",
      "cells": [
        "Beards/02"
      ]
    },
    {
      "id": "03",
      "cells": [
        "Beards/03"
      ]
    },
    {
      "id": "04",
      "cells": [
        "Beards/04"
      ]
    },
    {
      "id": "05",
      "cells": [
        "Beards/05"
      ]
    },
    {
      "id": "06",
      "cells": [
        "Beards/06"
      ]
    },
    {
      "id": "07",
      "cells": [
        "Beards/07"
      ]
    },
    {
      "id": "08",
      "cells": [
        "Beards/08"
      ]
    },
    {
      "id": "09",
      "cells": [
        "Beards/09"
      ]
    },
    {
      "id": "10",
      "cells": [
        "Beards/10"
      ]
    },
    {
      "id": "11",
      "cells": [
        "Beards/11"
      ]
    },
    {
      "id": "12",
      "cells": [
        "Beards/12"
      ]
    },
    {
      "id": "13",
      "cells": [
        "Beards/13"
      ]
    }
  ],
  "hair_back": [
    {
      "id": "01",
      "cells": [
        "HairBack/01"
      ]
    },
    {
      "id": "02",
      "cells": [
        "HairBack/02"
      ]
    },
    {
      "id": "03",
      "cells": [
        "HairBack/03"
      ]
    },
    {
      "id": "04",
      "cells": [
        "HairBack/04"
      ]
    },
    {
      "id": "05",
      "cells": [
        "HairBack/05"
      ]
    },
    {
      "id": "06",
      "cells": [
        "HairBack/06"
      ]
    },
    {
      "id": "07",
      "cells": [
        "HairBack/07"
      ]
    },
    {
      "id": "08",
      "cells": [
        "HairBack/08"
      ]
    },
    {
      "id": "09",
      "cells": [
        "HairBack/09"
      ]
    },
    {
      "id": "10",
      "cells": [
        "HairBack/10"
      ]
    },
    {
      "id": "11",
      "cells": [
        "HairBack/11"
      ]
    },
    {
      "id": "12",
      "cells": [
        "HairBack/12"
      ]
    },
    {
      "id": "13",
      "cells": [
        "HairBack/13"
      ]
    },
    {
      "id": "14",
      "cells": [
        "HairBack/14"
      ]
    },
    {
      "id": "15",
      "cells": [
        "HairBack/15"
      ]
    },
    {
      "id": "16",
      "cells": [
        "HairBack/16"
      ]
    },
    {
      "id": "17",
      "cells": [
        "HairBack/17"
      ]
    },
    {
      "id": "18",
      "cells": [
        "HairBack/18"
      ]
    },
    {
      "id": "19",
      "cells": [
        "HairBack/19"
      ]
    },
    {
      "id": "20",
      "cells": [
        "HairBack/20"
      ]
    },
    {
      "id": "21",
      "cells": [
        "HairBack/21"
      ]
    },
    {
      "id": "22",
      "cells": [
        "HairBack/22"
      ]
    },
    {
      "id": "23",
      "cells": [
        "HairBack/23"
      ]
    },
    {
      "id": "24",
      "cells": [
        "HairBack/24"
      ]
    },
    {
      "id": "25",
      "cells": [
        "HairBack/25"
      ]
    },
    {
      "id": "26",
      "cells": [
        "HairBack/26"
      ]
    },
    {
      "id": "27",
      "cells": [
        "HairBack/27"
      ]
    }
  ],
  "hair_front": [
    {
      "id": "01",
      "cells": [
        "HairFront/01"
      ]
    },
    {
      "id": "02",
      "cells": [
        "HairFront/02"
      ]
    },
    {
      "id": "03",
      "cells": [
        "HairFront/03"
      ]
    },
    {
      "id": "04",
      "cells": [
        "HairFront/04"
      ]
    },
    {
      "id": "05",
      "cells": [
        "HairFront/05"
      ]
    },
    {
      "id": "06",
      "cells": [
        "HairFront/06"
      ]
    },
    {
      "id": "07",
      "cells": [
        "HairFront/07"
      ]
    },
    {
      "id": "08",
      "cells": [
        "HairFront/08"
      ]
    },
    {
      "id": "09",
      "cells": [
        "HairFront/09"
      ]
    },
    {
      "id": "10",
      "cells": [
        "HairFront/10"
      ]
    },
    {
      "id": "11",
      "cells": [
        "HairFront/11"
      ]
    },
    {
      "id": "12",
      "cells": [
        "HairFront/12"
      ]
    },
    {
      "id": "13",
      "cells": [
        "HairFront/13"
      ]
    },
    {
      "id": "14",
      "cells": [
        "HairFront/14"
      ]
    },
    {
      "id": "15",
      "cells": [
        "HairFront/15"
      ]
    },
    {
      "id": "16",
      "cells": [
        "HairFront/16"
      ]
    },
    {
      "id": "17",
      "cells": [
        "HairFront/17"
      ]
    },
    {
      "id": "18",
      "cells": [
        "HairFront/18"
      ]
    },
    {
      "id": "19",
      "cells": [
        "HairFront/19"
      ]
    },
    {
      "id": "20",
      "cells": [
        "HairFront/20"
      ]
    },
    {
      "id": "21",
      "cells": [
        "HairFront/21"
      ]
    },
    {
      "id": "22",
      "cells": [
        "HairFront/22"
      ]
    },
    {
      "id": "23",
      "cells": [
        "HairFront/23"
      ]
    },
    {
      "id": "24",
      "cells": [
        "HairFront/24"
      ]
    },
    {
      "id": "25",
      "cells": [
        "HairFront/25"
      ]
    },
    {
      "id": "26",
      "cells": [
        "HairFront/26"
      ]
    },
    {
      "id": "27",
      "cells": [
        "HairFront/27"
      ]
    }
  ],
  "scars": [
    {
      "id": "01",
      "cells": [
        "AccessoriesBelowBeard/01"
      ]
    },
    {
      "id": "04",
      "cells": [
        "AccessoriesBelowBeard/04"
      ]
    },
    {
      "id": "05",
      "cells": [
        "AccessoriesBelowBeard/05"
      ]
    },
    {
      "id": "10",
      "cells": [
        "AccessoriesBelowBeard/10"
      ]
    },
    {
      "id": "11",
      "cells": [
        "AccessoriesBelowBeard/11"
      ]
    }
  ],
  "blemishes": [
    {
      "id": "03",
      "cells": [
        "AccessoriesBelowBeard/03"
      ]
    },
    {
      "id": "07",
      "cells": [
        "AccessoriesBelowBeard/07"
      ]
    },
    {
      "id": "02",
      "cells": [
        "AccessoriesBelowBeard/02"
      ]
    },
    {
      "id": "14",
      "cells": [
        "AccessoriesBelowBeard/14"
      ]
    },
    {
      "id": "06",
      "cells": [
        "AccessoriesBelowBeard/06"
      ]
    },
    {
      "id": "09",
      "cells": [
        "AccessoriesBelowBeard/09"
      ]
    },
    {
      "id": "13",
      "cells": [
        "AccessoriesBelowBeard/13"
      ]
    },
    {
      "id": "08",
      "cells": [
        "AccessoriesBelowBeard/08"
      ]
    }
  ],
  "horns": [
    {
      "id": "05",
      "cells": [
        "LayeredAccessories/05",
        "LayeredAccessoryBack/05"
      ]
    },
    {
      "id": "04",
      "cells": [
        "LayeredAccessories/04",
        "LayeredAccessoryBack/04"
      ]
    }
  ],
  "eyewear": [
    {
      "id": "03",
      "cells": [
        "LayeredAccessories/03"
      ]
    },
    {
      "id": "11",
      "cells": [
        "LayeredAccessories/11"
      ]
    },
    {
      "id": "10",
      "cells": [
        "LayeredAccessories/10"
      ]
    },
    {
      "id": "07",
      "cells": [
        "LayeredAccessories/07"
      ]
    },
    {
      "id": "06",
      "cells": [
        "LayeredAccessories/06"
      ]
    },
    {
      "id": "08",
      "cells": [
        "LayeredAccessories/08"
      ]
    },
    {
      "id": "09",
      "cells": [
        "LayeredAccessories/09"
      ]
    }
  ],
  "jewellery": [
    {
      "id": "01",
      "cells": [
        "LayeredAccessories/01"
      ]
    },
    {
      "id": "02",
      "cells": [
        "LayeredAccessories/02"
      ]
    },
    {
      "id": "12",
      "cells": [
        "AccessoriesBelowBeard/12"
      ]
    }
  ],
  "earrings": [
    {
      "id": "stud-silver",
      "cells": [
        "Earrings/stud-silver-{ears}"
      ]
    },
    {
      "id": "stud-gold",
      "cells": [
        "Earrings/stud-gold-{ears}"
      ]
    },
    {
      "id": "hoop-silver",
      "cells": [
        "Earrings/hoop-silver-{ears}"
      ]
    },
    {
      "id": "hoop-gold",
      "cells": [
        "Earrings/hoop-gold-{ears}"
      ]
    },
    {
      "id": "bighoop-silver",
      "cells": [
        "Earrings/bighoop-silver-{ears}"
      ]
    },
    {
      "id": "bighoop-gold",
      "cells": [
        "Earrings/bighoop-gold-{ears}"
      ]
    },
    {
      "id": "drop-silver",
      "cells": [
        "Earrings/drop-silver-{ears}"
      ]
    },
    {
      "id": "drop-gold",
      "cells": [
        "Earrings/drop-gold-{ears}"
      ]
    },
    {
      "id": "dangle-silver",
      "cells": [
        "Earrings/dangle-silver-{ears}"
      ]
    },
    {
      "id": "dangle-gold",
      "cells": [
        "Earrings/dangle-gold-{ears}"
      ]
    }
  ],
  "jewellery2": [
    {
      "id": "01",
      "cells": [
        "LayeredAccessories/01"
      ]
    },
    {
      "id": "02",
      "cells": [
        "LayeredAccessories/02"
      ]
    },
    {
      "id": "12",
      "cells": [
        "AccessoriesBelowBeard/12"
      ]
    }
  ]
};
