// GENERATED by scripts/build-face-manifest.mjs — do not edit by hand.
// Artwork: V-ktor/pixel-art-portraits, MIT. See assets/faces/LICENSE.

export type FaceAsset = {
  name: string;
  shadow: boolean;
  /** cloths: the sub-layers of one outfit. */
  parts?: string[];
  /** hair: a clip belonging to this style. */
  decoration?: boolean;
  /** hair: the front piece this style draws over the forehead. */
  front?: string | null;
  frontShadow?: boolean;
  /** hair accessories live in two directories; this is the real path. */
  path?: string;
};

export const MANIFEST: Record<string, FaceAsset[]> = {
  "body": [
    {
      "name": "female01",
      "shadow": false
    },
    {
      "name": "female02",
      "shadow": false
    },
    {
      "name": "female03",
      "shadow": false
    },
    {
      "name": "female_android",
      "shadow": false
    },
    {
      "name": "male01",
      "shadow": false
    },
    {
      "name": "male02",
      "shadow": false
    },
    {
      "name": "male03",
      "shadow": false
    },
    {
      "name": "male_android",
      "shadow": false
    }
  ],
  "cloths": [
    {
      "name": "female01",
      "shadow": true,
      "parts": [
        "primary",
        "secondary",
        "details"
      ]
    },
    {
      "name": "female02",
      "shadow": true,
      "parts": [
        "primary",
        "secondary",
        "details"
      ]
    },
    {
      "name": "female03",
      "shadow": true,
      "parts": [
        "primary"
      ]
    },
    {
      "name": "female04",
      "shadow": true,
      "parts": [
        "primary",
        "secondary"
      ]
    },
    {
      "name": "female05",
      "shadow": true,
      "parts": [
        "primary",
        "secondary"
      ]
    },
    {
      "name": "female06",
      "shadow": true,
      "parts": [
        "primary",
        "secondary"
      ]
    },
    {
      "name": "female07",
      "shadow": true,
      "parts": [
        "primary",
        "secondary"
      ]
    },
    {
      "name": "female08",
      "shadow": true,
      "parts": [
        "primary"
      ]
    },
    {
      "name": "female09",
      "shadow": true,
      "parts": [
        "primary"
      ]
    },
    {
      "name": "female10",
      "shadow": true,
      "parts": [
        "primary"
      ]
    },
    {
      "name": "female11",
      "shadow": true,
      "parts": [
        "primary",
        "secondary"
      ]
    },
    {
      "name": "female12",
      "shadow": true,
      "parts": [
        "primary",
        "secondary",
        "details"
      ]
    },
    {
      "name": "male01",
      "shadow": true,
      "parts": [
        "primary"
      ]
    },
    {
      "name": "male02",
      "shadow": true,
      "parts": [
        "primary"
      ]
    },
    {
      "name": "male03",
      "shadow": true,
      "parts": [
        "primary",
        "secondary"
      ]
    },
    {
      "name": "male04",
      "shadow": true,
      "parts": [
        "primary",
        "secondary"
      ]
    },
    {
      "name": "male05",
      "shadow": true,
      "parts": [
        "primary",
        "secondary",
        "details"
      ]
    },
    {
      "name": "male06",
      "shadow": true,
      "parts": [
        "primary",
        "secondary"
      ]
    },
    {
      "name": "male07",
      "shadow": true,
      "parts": [
        "primary"
      ]
    },
    {
      "name": "male08",
      "shadow": true,
      "parts": [
        "primary",
        "secondary",
        "details"
      ]
    }
  ],
  "neck": [
    {
      "name": "bow",
      "shadow": false
    },
    {
      "name": "collar",
      "shadow": false
    },
    {
      "name": "necklace",
      "shadow": false
    },
    {
      "name": "scarf",
      "shadow": false
    },
    {
      "name": "tie",
      "shadow": false
    }
  ],
  "mouth": [
    {
      "name": "O",
      "shadow": false
    },
    {
      "name": "grin01",
      "shadow": false
    },
    {
      "name": "grin02",
      "shadow": false
    },
    {
      "name": "neutral",
      "shadow": false
    },
    {
      "name": "neutral01",
      "shadow": false
    },
    {
      "name": "neutral02",
      "shadow": false
    },
    {
      "name": "sad01",
      "shadow": false
    },
    {
      "name": "sad02",
      "shadow": false
    },
    {
      "name": "small",
      "shadow": false
    },
    {
      "name": "smile01",
      "shadow": false
    },
    {
      "name": "smile02",
      "shadow": false
    }
  ],
  "nose": [
    {
      "name": "large01",
      "shadow": false
    },
    {
      "name": "large02",
      "shadow": false
    },
    {
      "name": "neutral01",
      "shadow": false
    },
    {
      "name": "neutral02",
      "shadow": false
    },
    {
      "name": "pointy01",
      "shadow": false
    },
    {
      "name": "pointy02",
      "shadow": false
    },
    {
      "name": "small01",
      "shadow": false
    },
    {
      "name": "small02",
      "shadow": false
    }
  ],
  "beard": [
    {
      "name": "beard01",
      "shadow": true
    },
    {
      "name": "beard02",
      "shadow": true
    },
    {
      "name": "beard03",
      "shadow": true
    },
    {
      "name": "beard04",
      "shadow": true
    },
    {
      "name": "beard05",
      "shadow": true
    },
    {
      "name": "moustache",
      "shadow": true
    }
  ],
  "eyes": [
    {
      "name": "angled01",
      "shadow": true
    },
    {
      "name": "closed01",
      "shadow": true
    },
    {
      "name": "closed02",
      "shadow": true
    },
    {
      "name": "closed03",
      "shadow": true
    },
    {
      "name": "closed04",
      "shadow": true
    },
    {
      "name": "female01",
      "shadow": false
    },
    {
      "name": "female02",
      "shadow": false
    },
    {
      "name": "female03",
      "shadow": false
    },
    {
      "name": "flat01",
      "shadow": false
    },
    {
      "name": "flat02",
      "shadow": false
    },
    {
      "name": "male01",
      "shadow": true
    },
    {
      "name": "male02",
      "shadow": true
    },
    {
      "name": "male03",
      "shadow": true
    },
    {
      "name": "tall01",
      "shadow": false
    }
  ],
  "brows": [
    {
      "name": "angry01",
      "shadow": false
    },
    {
      "name": "angry02",
      "shadow": false
    },
    {
      "name": "flat01",
      "shadow": false
    },
    {
      "name": "flat02",
      "shadow": false
    },
    {
      "name": "neutral01",
      "shadow": false
    },
    {
      "name": "neutral02",
      "shadow": false
    },
    {
      "name": "neutral03",
      "shadow": false
    },
    {
      "name": "sad01",
      "shadow": false
    },
    {
      "name": "sad02",
      "shadow": false
    }
  ],
  "glasses": [
    {
      "name": "eye_patch01_left",
      "shadow": true
    },
    {
      "name": "eye_patch01_right",
      "shadow": true
    },
    {
      "name": "eye_patch02_left",
      "shadow": true
    },
    {
      "name": "eye_patch02_right",
      "shadow": true
    },
    {
      "name": "glasses01",
      "shadow": true
    },
    {
      "name": "glasses01_reflection",
      "shadow": true
    },
    {
      "name": "glasses02",
      "shadow": true
    },
    {
      "name": "glasses02_reflection",
      "shadow": true
    },
    {
      "name": "glasses03",
      "shadow": true
    },
    {
      "name": "glasses03_reflection",
      "shadow": true
    },
    {
      "name": "glasses04",
      "shadow": true
    },
    {
      "name": "glasses04_reflection",
      "shadow": true
    },
    {
      "name": "monocle",
      "shadow": true
    }
  ],
  "hair/base": [
    {
      "name": "female01",
      "shadow": true,
      "decoration": true,
      "front": "female01",
      "frontShadow": true
    },
    {
      "name": "female02",
      "shadow": true,
      "decoration": true,
      "front": "female02",
      "frontShadow": true
    },
    {
      "name": "female03",
      "shadow": true,
      "decoration": true,
      "front": "female03",
      "frontShadow": true
    },
    {
      "name": "female04",
      "shadow": true,
      "decoration": true,
      "front": "female04",
      "frontShadow": true
    },
    {
      "name": "female06",
      "shadow": true,
      "decoration": true,
      "front": "female06",
      "frontShadow": true
    },
    {
      "name": "female07",
      "shadow": true,
      "decoration": true,
      "front": "female07",
      "frontShadow": true
    },
    {
      "name": "female08",
      "shadow": true,
      "decoration": true,
      "front": "female08",
      "frontShadow": false
    },
    {
      "name": "female09",
      "shadow": true,
      "decoration": true,
      "front": "female09",
      "frontShadow": false
    },
    {
      "name": "female10",
      "shadow": true,
      "decoration": true,
      "front": "female10",
      "frontShadow": true
    },
    {
      "name": "female11",
      "shadow": true,
      "decoration": true,
      "front": "female11",
      "frontShadow": true
    },
    {
      "name": "female12",
      "shadow": true,
      "decoration": true,
      "front": "female12",
      "frontShadow": true
    },
    {
      "name": "female14",
      "shadow": true,
      "decoration": true,
      "front": null,
      "frontShadow": false
    },
    {
      "name": "male01",
      "shadow": true,
      "decoration": true,
      "front": "male01",
      "frontShadow": true
    },
    {
      "name": "male02",
      "shadow": true,
      "decoration": true,
      "front": "male02",
      "frontShadow": false
    },
    {
      "name": "male03",
      "shadow": true,
      "decoration": true,
      "front": "male03",
      "frontShadow": true
    },
    {
      "name": "male04",
      "shadow": true,
      "decoration": true,
      "front": null,
      "frontShadow": false
    },
    {
      "name": "male06",
      "shadow": true,
      "decoration": true,
      "front": null,
      "frontShadow": false
    },
    {
      "name": "male07",
      "shadow": true,
      "decoration": true,
      "front": null,
      "frontShadow": false
    },
    {
      "name": "male10",
      "shadow": true,
      "decoration": true,
      "front": null,
      "frontShadow": false
    },
    {
      "name": "ponytail01",
      "shadow": true,
      "decoration": true,
      "front": null,
      "frontShadow": false
    }
  ],
  "hair/back": [
    {
      "name": "curly01",
      "shadow": false
    },
    {
      "name": "long01",
      "shadow": false
    },
    {
      "name": "long02",
      "shadow": false
    },
    {
      "name": "long03",
      "shadow": false
    },
    {
      "name": "medium01",
      "shadow": false
    },
    {
      "name": "medium02",
      "shadow": false
    },
    {
      "name": "medium03",
      "shadow": false
    },
    {
      "name": "pigtails01",
      "shadow": false
    },
    {
      "name": "ponytail",
      "shadow": false
    },
    {
      "name": "right01",
      "shadow": false
    },
    {
      "name": "short01",
      "shadow": false
    }
  ],
  "ears": [
    {
      "name": "bear_ears01",
      "shadow": false
    },
    {
      "name": "bear_ears01_fluff",
      "shadow": false
    },
    {
      "name": "bear_ears01_skin",
      "shadow": false
    },
    {
      "name": "bunny_ears01",
      "shadow": false
    },
    {
      "name": "cat_ears01",
      "shadow": false
    },
    {
      "name": "cat_ears01_fluff",
      "shadow": false
    },
    {
      "name": "cat_ears01_skin",
      "shadow": false
    },
    {
      "name": "dog_ears01",
      "shadow": false
    },
    {
      "name": "dog_ears01_fluff",
      "shadow": false
    },
    {
      "name": "fox_ears01",
      "shadow": false
    },
    {
      "name": "fox_ears01_fluff",
      "shadow": false
    },
    {
      "name": "fox_ears01_skin",
      "shadow": false
    },
    {
      "name": "fox_ears02",
      "shadow": false
    },
    {
      "name": "fox_ears02_fluff",
      "shadow": false
    },
    {
      "name": "fox_ears02_skin",
      "shadow": false
    }
  ],
  "horns": [
    {
      "name": "dragon_horns01",
      "shadow": false
    },
    {
      "name": "long01",
      "shadow": false
    },
    {
      "name": "massive01",
      "shadow": false
    },
    {
      "name": "short01",
      "shadow": false
    }
  ],
  "hair/accessory": [
    {
      "name": "earrings",
      "path": "hair/base/earrings",
      "shadow": false
    },
    {
      "name": "headset",
      "path": "hair/base/headset",
      "shadow": false
    },
    {
      "name": "ribbon",
      "path": "hair/base/ribbon",
      "shadow": false
    },
    {
      "name": "ear_cover01",
      "path": "hair/front/ear_cover01",
      "shadow": false
    },
    {
      "name": "ear_cover02",
      "path": "hair/front/ear_cover02",
      "shadow": false
    },
    {
      "name": "ear_cover03",
      "path": "hair/front/ear_cover03",
      "shadow": false
    },
    {
      "name": "ear_cover04",
      "path": "hair/front/ear_cover04",
      "shadow": false
    }
  ]
};
